version: '3.1'
networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
services:
  web:
    image: nginx:1.25.3
    container_name: web
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro
    environment:
      TZ: Asia/Shanghai
  php:
    # image: php:8.2-fpm
    build:
      context: .
      dockerfile: Phpdockerfile
    image: php:8.2fpm-composer-node-npm
    container_name: php82
    volumes: 
      - ./apps:/home/www/apps
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #mysql root账号密码
      MYSQL_USER: "www" #mysql普通用户账号
      MYSQL_PASSWORD: "www123" #mysql 普通账号密码
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d #mysql配置文件目录
      - ./mysql/data:/var/lib/mysql #mysql数据存放目录
      - ./mysql/logs:/var/log/mysqld # mysql错误日志
    networks:
      internal_net:
        ipv4_address: 172.16.0.10
    ports:
      - 3306:3306
  redis:
    image: redis:7.2.2
    container_name: redis
    restart: always
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.16.0.40
    ports:
      - 6379:6379
    volumes: 
      - ./redis/logs:/redis/logs    #日志文件地址是在配置文件中配置的[logfile项]，宿主容器映射日志文件目录要与配置文件中的日志目录一致
      - ./redis/data:/data  # 持久化数据
      - ./redis/conf:/redis/conf # 在宿主机./redis/conf/下放redis.conf配置文件，注意需要将 daemonized 配置项注释掉（该配置项控制是否后台运行），否则容器运行后貌似无法探活，docker认为服务未启动会一直重启
    command: redis-server  /redis/conf/redis.conf # 启动redis-server 配置文件路径要以容器中的路径为准
    environment:
      TZ: Asia/Shanghai
    
    
  redis-backup:
    image: redis:7.2.2
    container_name: redis-backup
    restart: always
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.16.0.50
    ports:
      - 6380:6379
    volumes: 
      - ./redis-backup/logs:/redis/logs    #日志文件地址是在配置文件中配置的[logfile项]，宿主容器映射日志文件目录要与配置文件中的日志目录一致
      - ./redis-backup/data:/data  # 持久化数据
      - ./redis-backup/conf:/redis/conf # 在宿主机./redis/conf/下放redis.conf配置文件，注意需要将 daemonized 配置项注释掉（该配置项控制是否后台运行），否则容器运行后貌似无法探活，docker认为服务未启动会一直重启
    command: redis-server  /redis/conf/redis.conf --slaveof 172.16.0.40 6379 # 启动redis-server 配置文件路径要以容器中的路径为准
    environment:
      TZ: Asia/Shanghai